export const User=[
    {
        id:1,
        profilePicture: "assest/person/1.jpeg",
        username : "Sanatt Mishra",
    },
    {
        id:2,
        profilePicture: "assest/person/2.jpeg",
        username : "prateek",
    },
    {
        id:3,
        profilePicture: "assest/person/3.jpeg",
        username : "shamim",
    },
    {
        id:4,
        profilePicture: "assest/person/4.jpeg",
        username : "Arib",
    },
    {
        id:5,
        profilePicture: "assest/person/5.jpeg",
        username : "Amit",
    },
    {
        id:6,
        profilePicture: "assest/person/6.jpeg",
        username : "aadrash",
    },
    {
        id:7,
        profilePicture: "assest/person/7.jpeg",
        username : "Kapil",
    },
    {
        id:8,
        profilePicture: "assest/person/8.jpeg",
        username : "Sindhuraj",
    },
    {
        id:9,
        profilePicture: "assest/person/9.jpeg",
        username : "Abhishek",
    },
    {
        id:10,
        profilePicture: "assest/person/10.jpeg",
        username : "Aditya",
    },                                                                                  
]

export const Posts=[
    {
      id:1,
      photo:"assest/post/1.jpeg",
      date: "5 min ago",
      userId:1,
      like:32,
      comment:9,
    },
    {
        id:2,
        photo:"assest/post/2.jpeg",
        date: "51 min ago",
        userId:2,
        like:33,
        comment:10,
      },
      {
        id:3,
        photo:"assest/post/3.jpeg",
        date: "55 min ago",
        userId:3,
        like:22,
        comment:7,
      },
      {
        id:4,
        photo:"assest/post/4.jpeg",
        date: "54 min ago",
        userId:4,
        like:34,
        comment:4,
      },
      {
        id:5,
        photo:"assest/post/5.jpeg",
        date: "55 min ago",
        userId:5,
        like:35,
        comment:5,
      },
      {
        id:6,
        photo:"assest/post/6.jpeg",
        date: "56 min ago",
        userId:6,
        like:36,
        comment:6,
      },
      {
        id:7,
        photo:"assest/post/7.jpeg",
        date: "57 min ago",
        userId:7,
        like:37,
        comment:7,
      },
      {
        id:8,
        photo:"assest/post/8.jpeg",
        date: "58 min ago",
        userId:8,
        like:38,
        comment:8,
      },
      {
        id:9,
        photo:"assest/post/9.jpeg",
        date: "59 min ago",
        userId:9,
        like:39,
        comment:9,
      },
      {
        id:10,
        photo:"assest/post/10.jpeg",
        date: "50 min ago",
        userId:10,
        like:30,
        comment:10,
      },
]
